### ISSUE TITLE
Metadata Synchronization Test

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#16]
- Master: dev:8084 -> stop NRC
- Slave: dev2:8082
- [Client doc](https://docs.google.com/document/d/1p8VQW7qavZsdEehKLKDFQeR0rAeBxMnSlqS8R5Xn8MA/edit#)
- [Documentation and extra app needed for testing](https://drive.google.com/drive/u/0/folders/1nM_wUANLs4LbYWEgg_5rvuaVjiI699sV)

- [x] Clone dev:8082 -> dev:8084
- [x] Start with clean DB (both) 
- [x] Import app metadata (only master)
- [x] Define test, document all steps for master -> slave (metadata) and slave -> master (data values): [google docs](https://docs.google.com/document/d/1zODUoLFTtL-XX-0aqejwNKLmR1_tHSK_y9WYlZ41a8g/edit)

Notes:  Look in particular for custom forms, note that dashboard won't be synced (future feature, for now if you want -> edit -> save).

**Comment by adrianq** [comment]
We have received a new version of the management app and a metadata package. They can be found here: 
https://drive.google.com/drive/u/0/folders/1l9vjzkrwMvQBTDub1l12t1O86ythRHFe

The client said:

> 
Te adjunto la versión de la Management que permite crear versiones (hay un botón en el menú) , y un paquete de metadatos que habría que importar antes. Es necesario superuser para poder crearlas. Si no consigues hacerlo funcionar me dices.

@tokland once we merge most of the pending PRs we should give it a try with these new versions

**Comment by tokland** [comment]
Error on HMIS-Management: *Create version -> Create version*

`TypeError: Cannot read property 'id' of undefined`

On the network tab, we see there is this call:

`http://localhost:8085/api/sqlViews?filter=displayName:eq:swap_versions`

But this sqlView does not exist on the dumps we have nor on the staging server.
