### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#161]

**Comment by tokland** [comment]
https://docs.google.com/document/d/1g5_9L9qnjjol2_Ng9D6Oc1lJc_nyvV34RrwcE6BgtQs/edit

https://docs.google.com/document/d/1W_OvwlZeAtCyay0SqHAmqY7zxAKZsI_nRsy5VtwqN84/edit

**Comment by matiasgarcia91** [comment]
Checked through both docs, corrected a few typos but nothing major. Looks good!

**Comment by adrianq** [comment]
I have added several comments in both documents. @tokland Please have a look at them and let me know if you want to discuss anything

**Comment by tokland** [comment]
@matiasgarcia91 I've completed my update for technical/user guide. You can use the release notes as a references about what's to be changed.

https://github.com/EyeSeeTea/vaccination-app-blessed/releases/tag/v0.3.0

Once done, we can move the issue again to Testing.
