### ISSUE TITLE
Doses

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#168]
The number of doses is defined per antigen. In Data Entry a new disaggregation (dose) per administered doses will be displayed.

Cholera: 2
Dengue: 2
Japanese Encephalitis: 2
Measles: 1
Meningitis Conjugate: 1
Meningitis Polysaccharide: 1
PCV: 3
Pertussis Penta: 3
Poliomyelitis Injectable: 1
Poliomyelitis Oral: 3
Typhoid Fever: 1
Yellow Fever: 1

- [x] Modify vaccination-metadata: Add new disaggregation level for data element doses administered. 
  - [x] Add category options: **Dose N**
  - [x] Add category: **Dose**.
  - [x] Add new category option group: **[Antigen] - Doses**,
- [x] vaccination-app: read new metadata to get doses by antigen.
- [x] Modify data entry custom form. Create a row for each dose
![image (3)](https://user-images.githubusercontent.com/6850223/59095026-68f65680-890f-11e9-9534-8707e757482d.png)
  - [x] If only one dose -> remove "Dose 1"
  - [x] Add total row when multiple doses even when no split.

- [x] Add info to save/summary step
- [ ] Modify Dashboard items (@matiasgarcia91 ) -> Under discussion
   - [x] Vaccines Table (4)
   - [x] Remove vaccines used  from vaccines table (pending discussion on new table with used, administered and utilization rate)

// These two below are in discussion and will probably not be disaggregated by doses
   - [ ] Campaign Coverage Chart (3)
   - [ ] Vaccine Campaign Coverage (7)
- [x] Update technical / user guide.

**Comment by matiasgarcia91** [comment]
There are some issues with disaggregating the required tables/charts with this new dimension. `Vaccines doses used` is not disaggregated by anything on data entry so the following happens:
- Vaccines table: Right side of the table turns up empty as there is no way to show `dosesUsed` disaggregated by `ageGroup` or `Doses`.
- Both coverage chart/tables: this indicator is calculated dividing `dosesAdministered` by `dosesUsed` so same issue arises, dhis can't calculate the disaggregation so charts turn up empty.

We could split the vaccines Administered/Used table into two
