### ISSUE TITLE
Get initial code from dhis2-app-skeleton

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/vaccination-app#2]
- [x] https://github.com/EyeSeeTea/dhis2-app-skeleton/tree/feature/initial-app/public
- [x] Disable feedback
- [x] Connect to Travis (note: https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn)
- [x] Connect to PoEditor (@adrianq)

**Comment by adrianq** [comment]
@tokland I have created the project in POEditor (https://poeditor.com/projects/view?id=229573) and add you as an Administrator. You should be able to connect and manage it. If you want once we have something in the development branch we can connect it together.
