### ISSUE TITLE
Review what is causing a 'query did not return' problem

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#212]
Random or real error?
![Screenshot from 2019-06-28 13-17-15](https://user-images.githubusercontent.com/6850223/60401923-3d6a3300-9b80-11e9-98bb-8309b96125e2.png)

**Comment by tokland** [comment]
I've been unable to reproduce it. I had seen it once on my local tests. From the screenshot, there was a mismatch between dataset/campaign and team, this could be the cause. Whenever happens again, let's reopen and check on existing data.

**Comment by adrianq** [comment]
Closing as tickets are managed from Clickup now
