### ISSUE TITLE
Adjust category option sharing settings (the ones that are new, such as Teams, are not shared with any user, preventing data entry)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#232]
It is enough if you can set the public access of all of them with Data -> Can capture and view
This apply to Teams and any other category option created as part of the tool that could not be reused. If you reused, the settings should be ok.

**Comment by adrianq** [comment]
See https://docs.google.com/document/d/1pxQ1WHktbjLMETHJAtZbYCGfHiOxxQvFk9RG8hMI_fk/edit for more information

**Comment by tokland** [comment]
We already identified this, until finer sharings for categoryOptions are needed, we changed their publicAccess to rwrw:

https://github.com/EyeSeeTea/vaccination-app/blob/63c102f8abf1bbda091e4e22e0441387cf0f5197/src/models/Teams.ts#L109
