### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/vaccination-app#240]
Dashboard customisation
- [x] Remove suffix (_adverseEvents)
- [x] Remove from global title _DASHBOARD
- [x] Substitute underscore with spaces

Translations
- [x] Add English and French translations in d2-ui-components
- [x] Add support in metadata for translation
- [x] Dashboard => Implement translations for titles
- [x] Live translations on custom form
   - [x] Save translations of category options (antigens) and data elements somewhere in the custom form (as JSON).
   - [x] Use the current user language setting (DB) to use that translations.

**Comment by adrianq** [comment]
I have deeply tested the three PRs and they seem to be working fine. I just found two very minor bugs:
- We show the message 'Validating...' (in English) on the campaign name textfield
- Age Range Disaggregation always show up in English, e.g. 5-14 y

I guess these two are not particularly easy to solve and we can live with them. However, there is another important bug that I think it is not related to these PRs. If you save a campaign with 8 antigens or more we are gettings an error. I think it has to do with a metadata call larger than 8K. @tokland I guess this is going to be particularly tricky to solve. Please have a look at it. We can discuss tomorrow if it makes sense to fix it for this release.

**Comment by tokland** [comment]
For future reference:

> We show the message 'Validating...' (in English) on the campaign name textfield

I've checked, we have simply to add prop `validatingLabelText` to `FormBuilder

> Age Range Disaggregation always show up in English, e.g. 5-14 y

With the last PR, we have all the infrastructure prepared if we want to translate the age ranges, we'll have to add entries to source-data->categoryOptions (consider reshaping the translation object using something custom and more compact, there will be a lot of categoryOptions translations if we are to translate all age ranges)
