### ISSUE TITLE
Investigate/Discuss what happens in data entry when dataset is closed. Can we hide close datasets or sth like this?

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#257]
- [x] Ask client

**Comment by tokland** [comment]
Conclusion, we could either:

- Delete old campaign data sets.
- Unassign orgUnits to campaign data sets.

These could be manual actions or have a "Close campaign" action (only for admins) that would perform it.

Not to implement now, but let's keep a note on that.
