### ISSUE TITLE
Implement validation in data entry form

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#262]
Investigation
- [ ] doses admin < doses used
   - [ ] Create Validation Rule
   - [ ] Add code to custom form:
$(document).on("dhis2.de.event.dataValueSaved", (...args) => {
   dhis2.de.validate(false, true)
});

- [ ] AEFI > 0
   - Alternative 1
   - [ ] Create validation rule skipping online check
   - [ ] Set up validation group, validation notification and scheduler
   - Alternative 2: Do something as with doses adm/used but with a custom message

**Comment by adrianq** [comment]
Decission:
- [ ] doses admin < doses used
   - [ ] Create Validation Rule
   - [ ] Show again 'Run Validation' button

- [ ] AEFI > 0
   - [ ] Create Validation Rule with message 'Please fill in the AEFI registration form'
   - [ ] Show validation rule automatically:
```
$(document).on("dhis2.de.event.dataValueSaved", (...args) => {
dhis2.de.validate(false, true)
});

```

**Comment by tokland** [comment]
- [ ] vaccination-metadata: Create a validation rule for each antigen (sum powerset of all cocs for antigens)
