### ISSUE TITLE
Cosmetics

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/vaccination-app#31]
- [x] Move help button in stepper (only show in current step)
- [x] Move Next/Prev buttons to the bottom
- [x] Remove share button (EST)
- [x] List per page = 20

**Comment by adrianq** [comment]
As discussed, to completely finish this card we need to:
- [ ] Move previous/next to the right and inside the paper
- [ ] Change colour to save button to blue ( as in Program Indicator)
- [ ] Add Cancel right to the save button

For now, I will merge this PR and move this card back to backlog
