### ISSUE TITLE
Step 4 Refinement

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#63]
Now:
- [x] As discussed, we probably want to parse the age range and sort them.
- [x] Add 'Loading' on save step for antigens/disaggregation as we currently have in OUs
- [x] We may think about a better name than disaggregation. -> `Indicators configuration`
- [x] All the cosmetics changes we discussed. 
  - Screenshots:
![screenshot from 2019-03-07 13-16-19](https://user-images.githubusercontent.com/24643/54028696-33be5900-41a6-11e9-80b7-64ac4d9659a7.png)
![screenshot from 2019-03-07 13-30-24](https://user-images.githubusercontent.com/24643/54028697-33be5900-41a6-11e9-9ed0-94fadcd420ff.png)
  - Some notes: leftBar -> height: 100%, box, use box-shadow like NRC, padding-right: 20px, font size for "disaggregation" -> 0.9em, margin-left for categories: 80px; label -> width: 200px (to align), change "ageGroup / ageGroup2" for "ageGroup, ageGroup2".

Now:
- Disaggregations in step4 (Gender and Age Group):
   - [x] If they are mandatory fields, check that at least one option has been selected by the user
   - [x] If they are not mandatory, allow to deactivate the field
   - [x] Even if they are not mandatory, do not allow to deselect all options, since the render in the form wouldn’t be good

- Modify compulsory data element: try with an asterisk or tick instead of a disabled checkbox

Later:
- [ ] We should add a button when editing the age range that says: 'Set default values'
- [ ] If we click on a different antigen while we are on disaggregation edit mode, edit mode should be turned off, i.e. if we go back to the antigen we shouldn't be editing any more
- [ ] When editing an age range, the stepper width seems to change. Not a big deal but a bit strange though.
- [ ] Why are you using SimpleCheckbox? Cannot we use d2-ui-component checkbox? Choose another name.
- [ ] RVC_CREATED_... attribute seems to be used in multiple places. Don't we want to centralise it in a single place? -> Yes, it should be done.

**Comment by adrianq** [comment]
@tokland I saw you ticked a few checkboxes but you haven't created a PR yet, right? I guess you are planning to do it tomorrow. Can you take care of these minor issues https://github.com/EyeSeeTea/vaccination-app/issues/59 as part of that PR?

**Comment by adrianq** [comment]
Sorry I have just seen you commit these changes in the disaggregation branch. I will try to merge that branch today. Anyway, if you can have a look at those minor issues it would be great. Thanks!

**Comment by tokland** [comment]
https://github.com/EyeSeeTea/vaccination-app/pull/97

**Comment by adrianq** [comment]
Most of the tasks have been implemented and the other items are not particularly relevant
