### ISSUE TITLE
Review why more periods than expected are being displayed in data entry

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#74]

**Comment by tokland** [comment]
The problem is that form.js from data entry is using ds.startDate, ds.endDate, which do not exist. Issue open upstream:

https://jira.dhis2.org/browse/DHIS2-6240

We will be able to filter those values once we show the data entry in an iframe.

**Comment by adrianq** [comment]
@tokland Let's talk about this tomorrow. It looks like some kind of validation is actually happening. See 
![image](https://user-images.githubusercontent.com/6850223/56099761-1436f080-5f09-11e9-88ba-ea5fd802f43a.png)

Being start date: 10/4/2019

I was implementing the code to customise the dropdown but it may be it is not actually needed
