### ISSUE TITLE
Translations are not parsed from ts/tsx files

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/vaccination-app#81]
package-json -> extract-pot -> d2-i18n-extract, does not pass custom extensions, default are js/jsx.

See:

https://github.com/dhis2/d2-i18n-extract/blob/master/index.js

https://github.com/i18next/i18next-scanner

**Comment by tokland** [comment]
Extensions are harcoded in d2-i18n-extract, I've open a PR upstream:

https://github.com/dhis2/d2-i18n-extract/pull/4

I'd say to wait for the PR to be merged and published. For now, we can use our fork and link within the app:

```
$ git clone --branch=add-typescript-extensions git@github.com:tokland/d2-i18n-extract.git
$ yarn install
$ yarn link
$ cd /path/to/vaccination-app
$ yarn link "@dhis2/d2-i18n-extract"
```

Also, I opened this PR regarding missing translations:

https://github.com/EyeSeeTea/vaccination-app/pull/122

**Comment by adrianq** [comment]
@matiasgarcia91 Remember to do this once you are back to vaccination-app
