### ISSUE TITLE
Enhance dashboards

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/vaccination-app#82]
See https://docs.google.com/document/d/1aA8zvUdV_nWva6Uk9a7mJw5tLH9vjr8jcr6hJ6Scwk4/edit

**Comment by matiasgarcia91** [comment]
Comments:
AEFI Data element can't be disaggregated by "Minor/Severe"  in same Quality of Service table, it must be extracted to it's own table if we need this.

ToDo:
- [ ] Change orgUnitId for orgUnitName in chart/table name.
- [ ] Add team categoryCode to metadata filter on getDashboardItemsMetadata
- [ ] Connect extra disaggregation types from wizard's step 4 (according to the document we currently only need AgeGroup and targetPopulation/displacement but it can be useful to also include Gender or other types that might be requested in the future)
